name: Example Validate Configs

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  validate-configs:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |

        sudo apt-get update \
          && sudo apt-get install libusb-1.0-0-dev libxmu-dev libxmu-headers \
          freeglut3-dev libxext-dev libxi-dev libudev1 libudev-dev

        python -m pip install --upgrade pip
        pip install figgy-cli

    - name: Validate configs. This will fail!
      env:
        OVERRIDE_KEYRING: true
        CONFIG_FILE: ${{ secrets.CONFIG_FILE }}
        CREDENTIALS_FILE: ${{ secrets.CREDENTIALS_FILE }}
      run: |
        # Write out the [figgy-qa] profile with valid credentials
        mkdir -p ~/.aws
        echo "$CONFIG_FILE" > ~/.aws/config
        echo "$CREDENTIALS_FILE" > ~/.aws/credentials

        # Run validate on our QA account.
        figgy config validate --profile figgy-qa --config .github/examples/figgy.json
